/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OnTap;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author latu2
 */
public class frmMenu extends javax.swing.JFrame {
    JEditorPane edPage = new JEditorPane();
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        toolBNewFile = new javax.swing.JButton();
        toolBAbout = new javax.swing.JButton();
        toolBExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnFileNew = new javax.swing.JMenuItem();
        mnFileOpen = new javax.swing.JMenuItem();
        mnFileSave = new javax.swing.JMenuItem();
        mnColor = new javax.swing.JMenu();
        mnColorRed = new javax.swing.JRadioButtonMenuItem();
        mnColorGreen = new javax.swing.JRadioButtonMenuItem();
        mnColorBlue = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnColorTestColor = new javax.swing.JMenuItem();
        mnSystem = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        toolBNewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons On tap Bai 1/Icons_menu/document-32.png"))); // NOI18N
        toolBNewFile.setFocusable(false);
        toolBNewFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolBNewFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolBNewFileActionPerformed(evt);
            }
        });
        jToolBar1.add(toolBNewFile);

        toolBAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons On tap Bai 1/Icons_menu/user.png"))); // NOI18N
        toolBAbout.setFocusable(false);
        toolBAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolBAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolBAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(toolBAbout);

        toolBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons On tap Bai 1/Icons_menu/shut_down.png"))); // NOI18N
        toolBExit.setFocusable(false);
        toolBExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolBExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolBExitActionPerformed(evt);
            }
        });
        jToolBar1.add(toolBExit);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jButton4.setText("Color");

        mnFile.setText("File");

        mnFileNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFileNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons On tap Bai 1/Icons_menu/document-32.png"))); // NOI18N
        mnFileNew.setText("New");
        mnFile.add(mnFileNew);

        mnFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFileOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons On tap Bai 1/Icons_menu/open-file.png"))); // NOI18N
        mnFileOpen.setText("Open");
        mnFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFileOpenActionPerformed(evt);
            }
        });
        mnFile.add(mnFileOpen);

        mnFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFileSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons On tap Bai 1/Icons_menu/file-zip-alt-32.png"))); // NOI18N
        mnFileSave.setText("Save");
        mnFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFileSaveActionPerformed(evt);
            }
        });
        mnFile.add(mnFileSave);

        jMenuBar1.add(mnFile);

        mnColor.setText("Color");

        mnColorRed.setSelected(true);
        mnColorRed.setText("Red");
        mnColorRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorRedActionPerformed(evt);
            }
        });
        mnColor.add(mnColorRed);

        mnColorGreen.setSelected(true);
        mnColorGreen.setText("Green");
        mnColorGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorGreenActionPerformed(evt);
            }
        });
        mnColor.add(mnColorGreen);

        mnColorBlue.setSelected(true);
        mnColorBlue.setText("Blue");
        mnColorBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorBlueActionPerformed(evt);
            }
        });
        mnColor.add(mnColorBlue);
        mnColor.add(jSeparator1);

        mnColorTestColor.setText("Test Color");
        mnColor.add(mnColorTestColor);

        jMenuBar1.add(mnColor);

        mnSystem.setText("System");

        mnAbout.setText("About us");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        mnSystem.add(mnAbout);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnSystem.add(mnExit);

        jMenuBar1.add(mnSystem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorBlueActionPerformed
        txtArea.setBackground(Color.blue);
    }//GEN-LAST:event_mnColorBlueActionPerformed

    private void mnFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFileOpenActionPerformed
        JFileChooser fchooser = new JFileChooser();
        int result = fchooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try{
                edPage.setPage("file:///"+ fchooser.getSelectedFile().getPath());
            }
            catch(IOException ex)
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnFileOpenActionPerformed

    private void mnFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFileSaveActionPerformed
        JFileChooser fchooser = new JFileChooser();
        int result = fchooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fname = fchooser.getSelectedFile();
            try{
                PrintWriter pw =new PrintWriter(fname);
                pw.println(edPage.getText());
                pw.close();
            }
            catch(IOException ex)
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnFileSaveActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        showAboutUs();
    }//GEN-LAST:event_mnAboutActionPerformed

    private void mnColorRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorRedActionPerformed
        txtArea.setBackground(Color.red);
    }//GEN-LAST:event_mnColorRedActionPerformed

    private void mnColorGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorGreenActionPerformed
        txtArea.setBackground(Color.green);
    }//GEN-LAST:event_mnColorGreenActionPerformed

    private void toolBNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolBNewFileActionPerformed
        edPage.setText("");
    }//GEN-LAST:event_toolBNewFileActionPerformed

    private void toolBAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolBAboutActionPerformed
        showAboutUs();
    }//GEN-LAST:event_toolBAboutActionPerformed

    private void toolBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolBExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_toolBExitActionPerformed
    private void showAboutUs(){
        String str = "Program Demo Menu";
        str+= "\nAuthor: Tu";
        str+= "\nLast UpDate: 1-4-2024";
        str+= "\nEducation: Universcity";
        JOptionPane.showMessageDialog(null, str,"Gioi Thieu",JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenu mnColor;
    private javax.swing.JRadioButtonMenuItem mnColorBlue;
    private javax.swing.JRadioButtonMenuItem mnColorGreen;
    private javax.swing.JRadioButtonMenuItem mnColorRed;
    private javax.swing.JMenuItem mnColorTestColor;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnFileNew;
    private javax.swing.JMenuItem mnFileOpen;
    private javax.swing.JMenuItem mnFileSave;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JButton toolBAbout;
    private javax.swing.JButton toolBExit;
    private javax.swing.JButton toolBNewFile;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
