/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chuong2;

/**
 *
 * @author Administrator
 */
public class Bai4 extends javax.swing.JFrame {

    private double a = 0;
    private String pheptoan = "";

    /**
     * Creates new form Bai4
     */
    public Bai4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnCanBac2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnPhanTram = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btn1PhanX = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnChuyenDau = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnGiai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSo.setEditable(false);
        txtSo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        jPanel1.setLayout(new java.awt.GridLayout(4, 5, 1, 1));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btnChia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnChia.setText("/");
        btnChia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnChia);

        btnCanBac2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCanBac2.setText("sqrt");
        btnCanBac2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCanBac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanBac2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanBac2);

        btn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btnNhan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnNhan.setText("X");
        btnNhan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhan);

        btnPhanTram.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPhanTram.setText("%");
        btnPhanTram.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPhanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanTramActionPerformed(evt);
            }
        });
        jPanel1.add(btnPhanTram);

        btn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        btnTru.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnTru.setText("-");
        btnTru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });
        jPanel1.add(btnTru);

        btn1PhanX.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn1PhanX.setText("1/x");
        btn1PhanX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn1PhanX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1PhanXActionPerformed(evt);
            }
        });
        jPanel1.add(btn1PhanX);

        btn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);

        btnChuyenDau.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnChuyenDau.setText("+/-");
        btnChuyenDau.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnChuyenDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDauActionPerformed(evt);
            }
        });
        jPanel1.add(btnChuyenDau);

        btnC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnC.setText("C");
        btnC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel1.add(btnC);

        btnCong.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCong.setText("+");
        btnCong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });
        jPanel1.add(btnCong);

        btnGiai.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGiai.setText("=");
        btnGiai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnGiai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSo)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        txtSo.setText("0");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnChuyenDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDauActionPerformed
        
    }//GEN-LAST:event_btnChuyenDauActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        a = Long.parseLong(txtSo.getText());
        if (a != 0) {
            pheptoan = "/";
            txtSo.setText("0");
        }
    }//GEN-LAST:event_btnChiaActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        a = Long.parseLong(txtSo.getText());
        if (a != 0) {
            pheptoan = "*";
            txtSo.setText("0");
        }
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        a = Long.parseLong(txtSo.getText());
        if (a != 0) {
            pheptoan = "-";
            txtSo.setText("0");
        }
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        a = Long.parseLong(txtSo.getText());
        if (a != 0) {
            pheptoan = "+";
            txtSo.setText("0");
        }
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnCanBac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanBac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCanBac2ActionPerformed

    private void btnPhanTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanTramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPhanTramActionPerformed

    private void btn1PhanXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1PhanXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1PhanXActionPerformed

    private void btnGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiActionPerformed
        double kq = 0;
        long b = Long.parseLong(txtSo.getText());
        if (pheptoan.length() > 0) {
            if (pheptoan.equals("+")) {
                kq = a + b;
                txtSo.setText(String.valueOf(kq));
            }
            else if (pheptoan.equals("-")) {
                kq = a - b;
                txtSo.setText(String.valueOf(kq));
            }
            else if (pheptoan.equals("*")) {
                kq = a * b;
                txtSo.setText(String.valueOf(kq));
            }
            else {
            kq = a / b;
            txtSo.setText(String.valueOf(kq));
            }
            pheptoan = "";
            a =0;
        }
        
        
        

    }//GEN-LAST:event_btnGiaiActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn1.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn2.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn3.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn4.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn5.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn6.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn7.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn8.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn9.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        String gt = txtSo.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long so = Long.parseLong(gt + btn0.getText());
            txtSo.setText(String.valueOf(so));
        }
    }//GEN-LAST:event_btn0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbtn1roduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1PhanX;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCanBac2;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnChuyenDau;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnGiai;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnPhanTram;
    private javax.swing.JButton btnTru;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSo;
    // End of variables declaration//GEN-END:variables
}
